### ISSUE TITLE
Windows installer automatically starts service, but sets Startup Type to Manual

### ISSUE THREAD

**Issue by congyiwu** [Azure/azure-relay-bridge#11]
The Windows installer automatically starts the azbridgesvc service, but sets its Startup Type to Manual.

This seems inconsistent.  If the installer automatically starts a background service, I'd expect to stay running after a restart.  If it shouldn't start up automatically after a restart, it probably shouldn't start up automatically during installation.

**Comment by jfggdl** [comment]
@congyiwu, Thanks for bringing this to our attention. 
The behavior that you are observing is by design. Running the service has billing implications. Hence, after a machine restart, the service does not start automatically. If you want the service to restart after a machine restart (in a production environment, for example), you can do so using Services Manager. 
During the installation a common use case is that you want to install it to start working right away on it and hence the service starts after it is installed. 

I hope this clarifies the rationale for the behavior. Please let me know if you have additional questions.

**Comment by congyiwu** [comment]
> During the installation a common use case is that you want to install it to start working right away on it and hence the service starts after it is installed.

The installer blindly overwrites "C:\ProgramData\Microsoft\Azure Relay Bridge\azbridge_config.svc.yml" (even if I'm doing an upgrade and the file already exists), so when the service starts, it never actually "works" immediately.  If config files were automatically reloaded when they're modified, then the design would be reasonable, but that appears to be broken for me...

I filed #12 and #13.  Feel free to close this.
