### ISSUE TITLE
RelayName doesn't support backslash

### ISSUE THREAD

**Issue by janvanveldhuizen** [Azure/azure-relay-bridge#29]
I want to define a hybrid connection to a sqlserverhost named like 'SERVERNAME\INSTANCE'.
This seems not to be accepted.

**Comment by dboretti** [comment]
Hi,
you can always try to use the IP Address of the host instead of using the SQL Server instance name
Second, if you've not already done pay attention to TCP protocol and port configuration in SQL Server because when using named instances like your case the SQL Server service is configured by default to use dynamic ports, this setting should be changed by using a fixed port like 1433 or a port number of choice

**Comment by dlstucki** [comment]
This is most likely a restriction related to ARM. ServiceBus Queues/Topics and EventHub EventHubs also don't allow backslashes. You could try forward-slash (I think this gets converted to tilde for ARM), or you could use the UserMetadata field of a HybridConnection to store whatever data you want.
